### ISSUE TITLE
Feature Request: Add Deluge to homepage dashboard.

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#542] opened 2017-07-27 10:32 UTC
I use SABnzbd and Deluge for my downloaders.
SAB, shows status on the homepage, and it would be excellent for my deluge queue to show as well.

Thank you, and keep up the fantastic job, love this app!

**Comment by Vorboid** [comment] 2017-08-21 09:55
Possible duplicate of #220

**Comment by causefx** [comment] 2017-10-06 01:52
Yes, duplicate of #220

**Closed by causefx** 2017-10-06 01:52 UTC
