### ISSUE TITLE
Backups are backing up previous backups (Recursively)

### ISSUE THREAD

**Issue by alex-cardenas** [causefx/Organizr#1913] opened 2023-02-04 05:25 UTC
###### Operating System: unraid
<hr>

##### Problem Description:
Backups are also backing up previous backups leading to increasingly larger file sizes. 

<hr>

##### Reproduction Steps:
Go to Settings > Backup
Manually create a backup
Note File size
Manually create another backup
Notice file size increase
Repeat.
I have mine set on cron weekly and to keep 20 backups. I got up to 152gb for my latest backup (for a total backup folder size of 300gb) before I noticed. 

<hr>

#### Errors on screen?  If so paste here:

```
None
```

**Comment by alex-cardenas** [comment] 2023-02-04 05:26
![FireShot Capture 003 - Settings - Organizr V2 - 192 168 1 3](https://user-images.githubusercontent.com/35149352/216750417-c76674da-ea85-4bb7-8034-e1f241a887fd.png)

**Comment by HalianElf** [comment] 2023-02-07 14:29
Dupe of #1891 , you need to update

**Closed as completed by HalianElf** 2023-02-07 14:29 UTC
Labels: 👉 Duplicate 👈

**Comment by alex-cardenas** [comment] 2023-02-07 14:44
I'm pulling this from DockerHub (through Unraid) and the last update was in May by rodexus. Every time I open OrganizrV2, I get the update notification but that is within the container and doing any of the following does nothing: clicking the notification's update now button, going to Settings > Main > Github > Force Install Branch, (from Unraid side) Force update; none of those actually update since, I think, it's pulling from [dockerhub](https://hub.docker.com/r/organizr/organizr/tags)

**Comment by HalianElf** [comment] 2023-02-07 14:56
Restart the container and check the container logs, it sounds like you got a lock file that's preventing the update script from actually working. If there is a lock file, remove it and either restart the container again or click the update popup in the settings.

**Comment by alex-cardenas** [comment] 2023-02-08 13:53
Checking the logs did show a lock file "index.lock" in a .git folder. I removed that it seems to have updated successfully - thank you.
