### ISSUE TITLE
[V2] Closing tabs opens settings's one

### ISSUE THREAD

**Issue by G4Zz0L1** [causefx/Organizr#1266] opened 2019-10-19 15:11 UTC
###### Operating System: Arch Linux
<hr>

I don't know if it's an intended behaviour or if it's a bug, but when I close an open tab (if there's more than one opened), the setting's one keeps opening and it won't close, until it's the last one to close.

Example:
I'll start like this
![image](https://user-images.githubusercontent.com/13220636/67147131-49dedc80-f292-11e9-9625-14e87941513f.png)

Then I open two tabs
![image](https://user-images.githubusercontent.com/13220636/67147160-9c1ffd80-f292-11e9-9c66-a384d2a2baa3.png)

When I try to close one open tab, Organizr switch to the settings one and open it, even if there's the other one already opened
![image](https://user-images.githubusercontent.com/13220636/67147186-dee1d580-f292-11e9-90b0-286f3436f5ee.png)

If I switch to settings and try to close it, it will reload the other tab, but settings remains opened, until I close all the others opened tab, and then I can close the settings too.

If it's a bug I can file a pull request.

**Comment by causefx** [comment] 2019-10-19 15:20
I can't reproduce this...  The default behavior is if you close a tab and no more are open, it will open the first tab in list.  Can you record a video/gif?

**Comment by G4Zz0L1** [comment] 2019-10-19 15:37
Pardon the flicker, I don't know how to make a better gif

https://imgur.com/a/ZlFbSWO

**Comment by causefx** [comment] 2019-10-19 15:40
LOL yeah that is weird and shouldn't be happening...  I'll check again

**Comment by G4Zz0L1** [comment] 2019-10-19 15:41
Tell me if you need something, I'll try to help the best I can

**Comment by causefx** [comment] 2019-10-19 18:24
fixed in dev!

**Closed as completed by causefx** 2019-10-19 18:24 UTC

**Comment by G4Zz0L1** [comment] 2019-10-19 18:40
Perfect! Thank you for the quick response!
