### ISSUE TITLE
Getting continual 502 Bad Gateway Errors with Organizr and Caddy Server

### ISSUE THREAD

**Issue by Magic815** [causefx/Organizr#390] opened 2017-06-16 14:47 UTC
So I'm on Windows 8.1, and use Caddy Server as my webserver.

While I've been able to get Organizr set up how I like it, I've noticed that about once every 6-12 hours, the Organizr homepage will stop loading and instead throw a 502 Bad Gateway error. A simple restart of the Caddy service always fixes it, but I'd love to get the setup to a point where it stops happening entirely.

For Caddy, I used the following templates for my [caddyfile](https://pastebin.com/bLVJ4vsN) and [common.conf](https://pastebin.com/dQDXKpux) file.

The services I've hooked into Organizr are:
 - Emby  (proxied through a subdomain 'emby.domain.com')
 - Sonarr  (proxied through a subpath 'domain.com/sonarr')
 - Radarr  (proxied through a subpath 'domain.com/radarr')
 - NZBGet  (proxied through a subpath 'domain.com/nzbget')
 - Deluge  (proxied through a subpath 'domain.com/deluge')

One thing to note is that when the 502 error hits, it **only** impacts the Organizr homepage. All direct URLs to my individual services are still active and can be reached. So it's not an issue of Caddy completely failing.

Looking through the Caddy error logs, I've found the following line items that might be involved:
```
::1 - - [12/Jun/2017:22:32:49 -0400] "GET /ajax.php?a=emby-streams HTTP/2.0" 502 40
::1 - - [14/Jun/2017:23:21:25 -0400] "POST /deluge/json HTTP/1.1" 502 40
::1 - - [15/Jun/2017:02:35:14 -0400] "GET /ajax.php?a=nzbget-update&list=listgroups HTTP/2.0" 502 40
::1 - - [15/Jun/2017:02:37:15 -0400] "GET /ajax.php?a=nzbget-update&list=history HTTP/2.0" 502 40
::1 - - [15/Jun/2017:09:53:42 -0400] "GET / HTTP/2.0" 502 40
```
Just let me know if there is any further info I can provide and testing I can do to help debug this issue.

**Comment by LastStarFighter** [comment] 2017-06-24 18:51
Your PHP is crashing! Adding in some PHP arguments to Windows "Environment Variables" should help.

PHP_FCGI_CHILDREN
3
           
PHP_FCGI_MAX_REQUESTS
128

These are the settings i went with but you can change them to better suit your needs.

**Comment by Magic815** [comment] 2017-06-24 23:28
Ah, interesting. So is that where I just open cmd.exe, and then type in the following?

setx PHP_FCGI_CHILDREN 3
setx PHP_FCGI_MAX_REQUESTS 128

Any documentation or background info on why 3 and 128 are recommended? Just curious!

**Comment by causefx** [comment] 2017-06-24 23:29
MAgic, can you report back after your tests if this works :)

**Comment by LastStarFighter** [comment] 2017-06-24 23:51
Yup that should work or just start typing "environment" into windows search and the option to "edit system environment variables - control panel" should show up if you want to use the gui to do so.

Why these settings is just personal preference honestly. I wanted my setup to be able to handle 3 simultaneous PHP requests so i picked 3 and since i'm "not" running a site that handles many PHP requests i set the respawn to happen after only 128 requests.  I figure the amounts of requests to my PHP FCGI process would be low and i wanted to make sure the process would get shutdown and respawn more often than not. You can get away with only have 1 or 2 children and setting the max requests to way higher so just experiment and see what works best for you.

**Comment by causefx** [comment] 2017-06-25 07:17
good work @LastStarFighter

**Comment by LastStarFighter** [comment] 2017-06-25 15:15
@causefx Thanks! 

Really loving what your doing with Organizr and coming from your first iteration, the progression and continued improvement is pretty amazing. I can't say thanks enough for all the hard work you are putting into the project!

**Comment by causefx** [comment] 2017-06-25 16:12
@LastStarFighter thanks man, I appreciate it.  Everyone keeps suggesting new things and I'm like that would be cool to do... LOL

**Comment by LastStarFighter** [comment] 2017-06-25 17:48
The work never ends! LOL

**Comment by goofballtech** [comment] 2017-06-25 19:35
I am going to give it a shot with my instance as well and see if it give the same results. I have been busy with work lately and haven't done much for this.  Thanks @laststarfighter for running this all down. Hopefully this solution fixes us both up. 

I had a .Cmd file closing and reopening caddy every 6 hours, worked well as a stop gap but certainly not the right way.

**Comment by Magic815** [comment] 2017-06-25 19:51
Ever since I put in those two environment variables, I haven't seen any 502 errors! It's been about 20 hours of up-time so far. If I happen across any more 502s, I'll reply back here - but otherwise, I think that fixed it! Thanks!

**Comment by LastStarFighter** [comment] 2017-06-25 19:58
I've been scouring the web for months to try and figure out why this happens and on linux it seems PHP can start and close PHP processes inherently from the earliest version but on Windows it's wasn't baked in until v7.1 and you have to enable the feature by setting the "PHP_FCGI_CHILDREN" environment variable.

It seems the default max requests is 500 and since FCGI_Children isn't enabled PHP just stops after it hits those 500 requests! Setting the children argument creates a "Parent" process that can control (open & close) the child processes which should allow it to recycle the processes so no more issues.........???? I'm thinking the max requests argument is less critical and could be omitted but still need to test this. 

Of course i could be totally off base and there is no cause and effect :)

**Comment by causefx** [comment] 2017-06-25 20:01
there may not be any cause and effect but there sure is CauseFX

god, i'm horrible at jokes.

**Comment by LastStarFighter** [comment] 2017-06-25 20:14
I enjoyed it! 👍

:P

**Comment by seanvree** [comment] 2017-07-01 10:20
Need to bookmark this cause I"ve been having PHP issues, but I have like 50 windows open and I didn't want to loose this.

**Comment by LastStarFighter** [comment] 2017-07-01 17:01
Wild conjecture with no real IIS expertise so take with a grain of salt........ but this could be a IIS (ARR) issue more then your PHP crashing since it seems that PHP is working fine from the screenshot. When your loading Radarr with Organizr it's doing a lot polling in the background and that will take time to complete. So when your doing a search in Radarr through Organizr IIS has to proxy that request and if it's busy with handling those Organizr PHP requests then it could timeout/drop the Radarr requests (ARR timeout is 30 seconds i believe). You could always check you IIS logs and get a more details on the errors and see what IIS says is going on.

**Comment by causefx** [comment] 2017-07-01 18:58
we used to see this error before even on nginx, if i recall correctly they were caused by improper reverse proxies.

**Comment by goofballtech** [comment] 2017-07-01 20:11
follow up....  I am now a week in with daily use and no issues. 

Now to figure out how to make organizr work as a single sign on... more headaches to come.

**Comment by seanvree** [comment] 2017-07-02 01:18
@LastStarFighter - @causefx 

it COULD be the rev proxy, 

But this is how I test it:

If I go to domain.com/radarr and search,   it's fine
but if I got to   domain.com/organizr/#radarr   then thats when I see the errors

so could that still be the rev proxy??

**Comment by causefx** [comment] 2017-07-02 01:54
Lemme ask Elmer again because he was the one that ran into those problems.

**Comment by seanvree** [comment] 2017-07-02 03:26
@causefx  - Yeah, I could def be IIS...and/or PHP  LMK, been seeing this issue off and on for a few months now

**Comment by seanvree** [comment] 2017-07-04 03:12
@causefx  . @LastStarFighter 

Yeah, so I'm seeing this error as well from time to time:

```
HTTP Error 500.0 - Internal Server Error
C:\PHP\7.1\php-cgi.exe - The FastCGI process exceeded configured activity timeout
```

Right now, in IIS, I have the following:

PHP: 7.1 x64
Instance MaxRequest:  200
Max Instances:  5
PHP_FCGI_MAX_REQUESTS:  500
Activity Timeout:  79
Idel Timeout: 300
Queue Length:  1000
Rapid Fails perminute: 10
Request timeout: 90
Signal before Terminate:  0

you can see my page config page here:  seanvree .com  / php

**Comment by LastStarFighter** [comment] 2017-07-04 04:36
Don't see anything out of the ordinary in your PHP setup and with IIS Max instances + Instance MaxRequest does the same as my above variables so you should be good there. The timeouts are hard to diagnose since it could be IIS, network, proxy/rewrite, apps issue or a combination of things. I haven't used IIS in years so hard to even know where to begin so hopefully @causefx can be more help.

**Comment by seanvree** [comment] 2017-07-04 09:19
@LastStarFighter  - thanks for the input, 

one last thing.   The "default" config MS recommends (link below) suggests to use max instances 4, with " InstanceMaxRequests to 10000." and "PHP_FCGI_MAX_REQUESTS environment variable and set its value to 10000."

Does that sound right?

source:  https://docs.microsoft.com/en-us/iis/application-frameworks/install-and-configure-php-applications-on-iis/using-fastcgi-to-host-php-applications-on-iis

**Comment by LastStarFighter** [comment] 2017-07-04 16:48
@seanvree There's a balance you need to find and the recommended config should be work for "most" people.

For a large scale site serving thousands of users and php pages every second, recycling the fastcgi processes too often can eat cpu resources and slow down the site.  On the other hand the longer a process is open the more ram it'll consume and the greater chance for it to run into issues so you want it to recycle enough. 

For a reverse proxy with a handful of users I feel it's better to set the requests a little lower since hitting 10,000 could mean days or weeks depending your user load and I personally want the fastcgi processes to recycle at least once a day. Won't hurt to try a few different configs to see if you have better results and if PHP really is the cause of your issues.

**Closed** 2017-07-10 01:45 UTC
