### ISSUE TITLE
V2b Install fails partially / site not reachable from other machines

### ISSUE THREAD

**Issue by Blackraz0r** [causefx/Organizr#905] opened 2018-07-05 19:40 UTC
###### Operating System: Ubuntu/Debian/Raspbian
<hr>

##### Problem Description:
After the installscript finishes, with last option "LE" (Lets encrypt /standard)
it fails to create a few files for the hosts in nginx available.
says "there is no shuch file"

after this i cant get to the site.
i tried via ip. also it does not show the :443 in netstat so also no https bind was created.

<hr>

##### Reproduction Steps:
setup a fresh ubuntu server install, give it static ip
follow this orders
https://github.com/causefx/Organizr/wiki/Linux-Installation
<hr>

#### Errors on screen?  If so paste here:

```
> Do you want to generate Let's Encrypt SSL certs as well? [y/n].
- n
chmod: cannot access '/etc/nginx/sites-available/dashboard.nerd-korea.local.conf': No such file or directory
> Site Created for dashboard.nerd-korea.local

/bin/sed: can't read /etc/nginx/sites-available/dashboard.nerd-korea.local.conf: No such file or directory
/bin/sed: can't read /etc/nginx/sites-available/dashboard.nerd-korea.local.conf: No such file or directory
/bin/sed: can't read /etc/nginx/sites-available/dashboard.nerd-korea.local.conf: No such file or directory
[ ok ] Reloading nginx configuration (via systemctl): nginx.service.

######################################################
         Organizr  Install Complete
######################################################

```

**Comment by elmerfdz** [comment] 2018-07-09 22:40
Can't reproduce this. Are you running this on a PI?

**Comment by elmerfdz** [comment] 2018-07-25 10:53
@Blackraz0r this should be fixed now, could you please update the script & try again, if you haven't got around this already?

**Closed** 2018-09-06 15:49 UTC
