### ISSUE TITLE
Support for localhost URLs

### ISSUE THREAD

**Issue by serialoverflow** [causefx/Organizr#49] opened 2017-01-19 19:59 UTC
Hi,

would you consider adding support for localhost urls?
Currently, neither http://localhost:32400 nor http://127.0.0.1:32400 work to access the locally running plex service for instance.

**Comment by rix1337** [comment] 2017-01-19 20:11
Duplicate of #20 ?

**Comment by serialoverflow** [comment] 2017-01-19 20:14
I don't see what this has to do with proxies. I'd say it's more of a bug since Organizr can resolve external URLs just fine.

**Comment by rix1337** [comment] 2017-01-19 20:15
Sounded like you were trying to access localhost outside your network ;)

Are you trying to access organizr through https?

**Comment by rix1337** [comment] 2017-01-19 20:16
Also append /web to your plex url!

**Comment by serialoverflow** [comment] 2017-01-19 20:19
I'm sorry, you are right, i am trying to access localhost outside the server network.
I didn't realize proxy functionality is necessary to make that work.

**Comment by causefx** [comment] 2017-01-19 21:18
Are you using apache or nginx?

**Comment by serialoverflow** [comment] 2017-01-19 21:19
nginx

**Comment by causefx** [comment] 2017-01-19 21:20
You create a location block to reverse proxy your Plex app.

**Comment by serialoverflow** [comment] 2017-01-19 21:21
I do reverse proxy all apps, e.g. proxy_pass http://localhost:32400

**Comment by causefx** [comment] 2017-01-19 21:34
same way as those.

`location /plex {
    proxy_pass http://localhost:32400;
}`
`location /web {
    proxy_pass http://localhost:32400/web;
}`

**Comment by causefx** [comment] 2017-01-19 21:37
or try this if it doesnt work:

```
location /web {
    proxy_pass http://localhost:32400;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

```
location /plex {
    proxy_pass http://localhost/web;
  }
```

**Comment by serialoverflow** [comment] 2017-01-19 21:55
I'm not sure if that is the correct way to approach this.
For one thing, i have more than 10 services I'd like to put into Organizr and basically none of them work as sublocations unless you figure out the correct url rewrites for each one and/or reconfigure the service to adjust the base URL.
Another reason is that i don't really want to expose those services as sublocations because i prefer subdomains. In my experience, services work much better on a separate subdomain.

**Comment by causefx** [comment] 2017-01-19 22:14
that's entirely up to you.  unless you reverse proxy them, subdomain them or open up the ports that is the only way you will access them.  I have all my services through reverse proxies and have them all secured using their own securities.  I have all of them in Organizr fine.

![image](https://cloud.githubusercontent.com/assets/16184466/22127625/ed4ef8b4-de59-11e6-80a9-38839dd4c2ed.png)

**Comment by serialoverflow** [comment] 2017-01-19 22:20
That's interesting. Do you use nginx? If so, would you mind sharing your sublocation configuration for these services?

**Comment by causefx** [comment] 2017-01-20 00:48
yea, sorry man just got home.

```
	location /tv {
		proxy_pass http://usenet.home.lab:8989;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /movie {
		proxy_pass https://usenet.home.lab:5050;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
	
	location /nzbget {
		proxy_pass https://usenet.home.lab:6789;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
	
	location /request {
                proxy_pass http://usenet.home.lab:3579;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

	location /plexpy {
                proxy_pass https://plex.home.lab:8181;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-Host    $server_name;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   $scheme;
		proxy_set_header    X-Forwarded-Ssl     on;
        }
	
	location /vpn {
		proxy_pass https://dns.home.lab:1194;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	location /unifi {
                proxy_pass https://unifi.home.lab:8443;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
	}

        location /nzbhydra {
                proxy_pass http://usenet.home.lab:5075/nzbhydra/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /music {
                proxy_pass https://usenet.home.lab:8181;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

```

**Comment by causefx** [comment] 2017-01-20 02:40
closing as this is a duplicate.  hope that conf helps you, if not hit me up and i'll help you.

**Closed by causefx** 2017-01-20 02:40 UTC
Labels: duplicate

**Comment by gogo199432** [comment] 2017-12-17 23:21
Hey, sorry for opening up this, but is there any chance you could tell me where to put these settings when I'm running a container version of Organizr? Can't seem to find the config file anywhere.
Using this image if it helps: https://hub.docker.com/r/lsioarmhf/organizr/

**Comment by 2sh33ts** [comment] 2019-01-24 06:08
@causefx: first off I love the idea of Organizr, but I am having trouble setting it up. I got it installed but each tab does not connect to it's respective service/app. I've read that localhost:port urls won't work and that reverse proxies are needed, but I can't seem to get them setup correctly. I feel like I am really close, but missing something. Any help you provide would be greatly appreciated.

Also, sorry if this is in the wrong place. I am new to GitHub and Don't see a direct message option.

**Comment by causefx** [comment] 2019-01-24 06:19
if you join our discord server we can help out.... i will be available tomorrow morning to help if needed :)

**Comment by 2sh33ts** [comment] 2019-01-24 22:10
This may be a stupid question but what is the discord server you speak of and how do I access it? I should have some free time today and tomorrow if you’re available. Thanks for the quick response too btw.

**Comment by causefx** [comment] 2019-01-24 22:33
https://organizr.app/discord
