### ISSUE TITLE
Healthcheck API call error

### ISSUE THREAD

**Issue by GAS85** [causefx/Organizr#1488] opened 2020-10-30 09:17 UTC
###### Install Type: Official Docker
<hr>

##### Problem Description:

Since short time not Healthchecks.io statuses being shown. In a log I can see:
```
HealthChecks  Connect Function - Error: cURL error 60: SSL certificate problem:  unable to get local issuer certificate [Execution Time: 116.3ms]
```

<hr>

##### Reproduction Steps:

Configure Healthchecks.io in organizer and see that no statuses being presented

<hr>

#### Errors on screen?  If so paste here:

```
Nothing being shown.
```

**Comment by HalianElf** [comment] 2020-10-30 09:31
Dupe of #1481

**Closed as completed by HalianElf** 2020-10-30 09:31 UTC
