### ISSUE TITLE
Update doesnt update

### ISSUE THREAD

**Issue by themaaft** [causefx/Organizr#1856] opened 2022-06-24 08:51 UTC
###### Operating System: Ubuntu
<hr>

##### Problem Description:
in the Web UI it shows an update is ready to install 2.1.2330. i click install and it says complete, then it says an update is ready to install - 2.1.2330, so it never actually installs the update

<hr>

##### Reproduction Steps:
as above

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment] 2022-06-24 15:48
Likely a dupe of #1852, check that your linux-update.sh has execute rights.

**Comment by mami7880** [comment] 2022-06-28 19:33
I had the same problem. Setting the execution flag was unsuccessful. I run the linux-update.sh manually from the command line and got the following error: 
`/html/scripts/linux-update.sh: line 23: unzip: command not found`
After installing unzip, the Organizr update ran without issue.

Maybe Ubuntu (I'm using the 20.04 server version) changed something because I'm sure Unzip was installed before.

**Comment by drinking12many** [comment] 2022-07-01 10:59
on a Truenas jail I had to install unzip, change permissions on linux-update.sh, and then run it with "bash ./linux-update.sh" and it updated.

**Comment by causefx** [comment] 2022-08-17 19:09
I wonder if I should have it check for the zip dependency

**Comment by causefx** [comment] 2022-08-17 19:10
was this installed via the Organizr installer Wizard?

**Closed as completed** 2022-11-16 03:47 UTC
Labels: no-issue-activity, closed-no-issue-activity
