### ISSUE TITLE
[V2] Ombi on homepage causes site to hang

### ISSUE THREAD

**Issue by vMotionFailed** [causefx/Organizr#1107] opened 2019-03-11 19:19 UTC
###### Operating System: Windows
<hr>

##### Problem Description:
When I enable the ombi on homepage option it takes a good 1.5-2 minutes to load and the entire site locks up in the meantime to the point where chrome asks if I want to kill the page.  Eventually it will load and work fine.  My servers seem to have enough resources to load everything, I have a feeling it has to do with the amount of requests and the cover artwork for each request.  The fastest and maybe easiest fix I'm thinking would be a field for "item limit" just like the Plex homepage module has for recently added.  Then maybe later on some caching mechanism or background loading/lazy loading could be added in.

<hr>

##### Reproduction Steps:

Enable Ombi on homepage, refresh and go to homepage. 
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment] 2019-03-11 19:26
How many items do you at the moment?


I tested on my site:

![image](https://user-images.githubusercontent.com/16184466/54151827-f1408a80-43f8-11e9-9a45-2e05ee6d33bb.png)


1.3s on a cleared cache.

**Comment by vMotionFailed** [comment] 2019-03-11 19:52
I'm not sure, maybe like 1 or 2 pending requests then 61 ombi pages of approved movie requests and 8 ombi pages of approved TV show requests.  I ran the chrome diagnostics three separate times for consistency, it shows that the homepage/connect is only 2.22s + the other at 1.66s but at the bottom you can see the load time is 2.3 minutes and the finish is 7.4min on one of them, but consistently the Finish time is >1min.  

Video of issue:
https://cloud.crucialpixel.com/s/9PPRZBNHAraYQsT

![Organizr1](https://user-images.githubusercontent.com/1287511/54152796-6ec5c400-4414-11e9-9162-17062f78239a.png)
![Organizr2](https://user-images.githubusercontent.com/1287511/54152797-6f5e5a80-4414-11e9-9ca1-350d6a630378.png)
![2019-03-11_15-49-54](https://user-images.githubusercontent.com/1287511/54153201-5d30ec00-4415-11e9-8431-81aa9253756d.png)

**Comment by causefx** [comment] 2019-03-11 19:58
Hmmm, with network panel open on refresh, do you see a service with a large amount on the waterfall?  or the line where it takes > 1m?

**Comment by vMotionFailed** [comment] 2019-03-11 20:16
Sorry, I'm not too failure with the chrome dev tools so I might need some help on how to collect that data.  I took screenshots of the waterfall data where I found the largest blocks, hopefully that's what you were looking for.  The first time I did it at the end, the second time I took a screenshot mid way right when it froze and at the end.  There's nothing in the list of requests that is larger than the 1.68s homepage/connect request that is shown in the very last screenshot.  Nothing seems to show a >1min time associated with it besides the bottom of the chrome dev tool window. 

First: 
![image](https://user-images.githubusercontent.com/1287511/54154348-185a8480-4418-11e9-9708-fbfcf0e7cb00.png)
![image](https://user-images.githubusercontent.com/1287511/54154366-20b2bf80-4418-11e9-88b8-733e2c74d3b4.png)
![image](https://user-images.githubusercontent.com/1287511/54154376-24dedd00-4418-11e9-9c76-77ece0f7f901.png)

Second: 
Mid-way right when it froze:
![image](https://user-images.githubusercontent.com/1287511/54154412-3cb66100-4418-11e9-9d4c-a63f1a87d3a6.png)
![image](https://user-images.githubusercontent.com/1287511/54154440-49d35000-4418-11e9-936d-c968ae3c4c50.png)

At completion: 
![image](https://user-images.githubusercontent.com/1287511/54154469-56f03f00-4418-11e9-8dfd-27378187f538.png)
![image](https://user-images.githubusercontent.com/1287511/54154572-8ef78200-4418-11e9-912e-c98bca49bf20.png)

**Comment by vMotionFailed** [comment] 2019-03-11 20:17
There's that huge gap in the waterfall as well which is why I selected certain areas to see them better.

**Comment by causefx** [comment] 2019-03-11 20:27
Can you see where zone.js is getting loaded from?  right click and open in new tab

**Comment by vMotionFailed** [comment] 2019-03-11 20:37
They all appear to go to my ombi site calling parts of the ombi API /api/v1/images/tv/80379 and the page content is cover artwork or 401 errors.  Some of them return this search API function which are getting http 401 errors when I browse to them.

401 error
https://ombi.everythingplex.com/api/v1/search/Tv/info/80379 


example of image :
https://ombi.everythingplex.com/api/v1/Images/tv/75760
Content
https://assets.fanart.tv/fanart/tv/75760/seasonposter/how-i-met-your-mother-536e5f884a543.jpg

**Comment by causefx** [comment] 2019-03-11 20:39
Is ombi preloading in background?  can you do the network test again with no tabs except homepage?

**Comment by vMotionFailed** [comment] 2019-03-11 21:03
Yes, I forgot I had ombi preloading, I disabled all tabs except for homepage and settings and I turned off preloading on everything.  Those zone files seem to be gone, and loadtime has improved but still a solid delay.  

I sectioned off the waterfall again to isolate the longer ones.  Besides the beginning one everything else is under 1s. But the finish time is still between 1-2min for some reason.  It appears it's almost exactly 35 seconds for the page to load as a user.  I used the stopwatch on my phone and clocked 35s before the page becomes responsive again twice in a row.

First run:
![image](https://user-images.githubusercontent.com/1287511/54157067-f2d07980-441d-11e9-9f19-353ad8816130.png)

Second Run:
![image](https://user-images.githubusercontent.com/1287511/54157083-f9f78780-441d-11e9-8506-7e03ccb78363.png)

**Comment by causefx** [comment] 2019-03-11 21:30
Ok, I will add in a limit and see if that helps it out.

**Comment by vMotionFailed** [comment] 2019-03-11 21:38
Thanks! Much appreciated, if there's anything else you need me to run or check on my end just let me know, I'd be happy to.

**Comment by causefx** [comment] 2019-03-12 18:58
This new option is in dev if you want to test.  Dev is usually merged with Master on Fridays...

**Comment by causefx** [comment] 2019-03-12 22:28
Please open this issue back up if the problem is still there after this patch.

**Closed as completed by causefx** 2019-03-12 22:28 UTC
