### ISSUE TITLE
Reidrect after ServerAuth successful login

### ISSUE THREAD

**Issue by nadiamoe** [causefx/Organizr#1690] opened 2021-08-12 14:47 UTC
###### Organizr Version: 
`organizr/organizr:latest` (`4cae9b3da789fbde1a825a593be805f130420de923d3a814445b1b7b59ced92a`)

###### Branch: Master/Develop

Docker default.

###### WebServer: Nginx/Apache

Docker default (nginx)

###### Operating System: Windows/MacOS/Ubuntu

Docker on linux

<hr>

##### Problem Description:

I'm trying to set up ServerAuth using an external nginx reverse proxy. This proxy would query Organizr for authentication and pass the request to a backend on success.

I have set up an `auth_request` directive pointing to `http://organizr.organizr.svc.cluster.local/api/v2/auth?group=4` (which correctly resolves and points to Organizr), as well as an internal location so when nginx gets a `401` from Organizr, the user is redirected to the Organizr login page, which would be the root URL for Organizr (`https://auth.mydomain.local` in ths example).

Setup _roughtly_ looks like this:

```
location = /_auth {
    internal;
    # Set a few headers, elided for brevity
    # proxy_set_header...
    proxy_pass http://organizr.organizr.svc.cluster.local/api/v2/auth?group=4;
}

location @login {
    internal;
    return 302 https://auth.mydomain.local/?return=$pass_access_scheme://$http_host$escaped_request_uri;
}

# The server I'm proxying
location ~* "^/.+" {
    auth_request /_auth
    error_page 401 = @login

    # proxy_pass to the server
}
```

This roughly works: On first access, nginx queries `http://organizr.organizr.svc.cluster.local/api/v2/auth?group=4` and gets a 401. The 401 triggers the `error_page`, which in turns redirects the user to `https://auth.mydomain.local/?return=$pass_access_scheme://$http_host$escaped_request_uri`.

However, after the user logs in, organizr does not redirect them back to the url specified in the `?return` parameter, so the user has to manually navigate again to the first site. This time, the request to the organizr api will succeed, and the proxied website will be displayed.

It would be great if, after the login screen, Organizr would check if any `redirect`, `rd`, or similar URL parameters are set, and if so, emit a redirect to that URL.

<hr>

##### Reproduction Steps:

Set up nginx with serverAuth with an external nginx proxy as described above.

**Comment by tronyx** [comment] 2021-08-12 14:52
This already works as intended, as it is a feature of Nginx and has nothing to do with Organizr. You just need to configure your error pages to do so:

`error_page 401 https://DOMAIN.APP/?error=$status&return=$scheme://$http_host$request_uri;
error_page 400 402 403 404 405 408 502 503 504 https://DOMAIN.APP/?error=$status;
proxy_intercept_errors on;
error_page 500 https://DOMAIN.APP/?error=401&return=$scheme://$http_host$request_uri;`

**Comment by HalianElf** [comment] 2021-08-12 14:52
The return parameter should be doing that so it seems like something with the way you're doing the redirect is losing it (or it's ending up providing the wrong url to the return)

**Comment by causefx** [comment] 2021-08-12 15:20
You can test if the URI is set if you logout of Organizr and open up the browser console... Goto Application tab and select Local Storage and your domain after navigating to Org with redirect query...

![image](https://user-images.githubusercontent.com/16184466/129223062-30e32c5a-c631-453d-8a64-d23018569b3a.png)

**Comment by nadiamoe** [comment] 2021-08-12 18:50
Hi,

Huge thanks for the quick response!

I am able to confirm nginx is doing its work. When I get redirected, I do so to the url with the `?return=` parameter.

I can also verify it is in the localStorage under the `uri` key: 
![DeepinScreenshot_select-area_20210812204709](https://user-images.githubusercontent.com/969721/129251756-79c24441-6041-4dfc-9583-36fb5c9a9941.png)

However after logging in, I get a blank screen and a notification with "Fatal error":

| View | Console |
|--|--|
| ![DeepinScreenshot_select-area_20210812204808](https://user-images.githubusercontent.com/969721/129252029-ec7a4aa0-3389-4858-bb5c-0f34ec6d5be5.png) | ![DeepinScreenshot_select-area_20210812204839](https://user-images.githubusercontent.com/969721/129252052-4830ff4e-a2ba-4d2a-bfc5-579e6983f326.png) |

I observe that I'm using `$escaped_request_uri`, which is producing the `%2F` at the end of my `return` parameter. Could this be the issue? 

---

Edit: I have manually removed the escaped `/` at the end of the `return` parameter and it seems to work now!

Is this intended behavior? I would expect URLs to be escaped when passed as URL parameters.

**Comment by causefx** [comment] 2021-08-12 20:42
Good catch, lemme do some testing on my end

**Comment by causefx** [comment] 2021-08-12 20:55
fixed in dev.

**Closed as completed by causefx** 2021-08-12 20:55 UTC

**Comment by nadiamoe** [comment] 2021-08-12 21:34
Superb @causefx, that sounds awesome!

Many thanks again for the super fast response time and fix, and to everyone that works on this! It's an awesome project ❤️
