### ISSUE TITLE
Plex oAuth not working with Admin account

### ISSUE THREAD

**Issue by moust4ki** [causefx/Organizr#1336] opened 2020-03-29 20:50 UTC
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Hello
I have a working Organizr for few weeks now. Today I was logged out of my account and when I tried to log back using Plex SSO I have the message 

> OAUTH Successfull, Please Wait

 and then a popup notification 

> Login Error - API connection Failed

However, I can login with differents accounts using Plex OAuth, it is only an issue with my admin account.

I logged using the Organizr login/Pass and I can see that my connection seems to be good (checkmark) using Plex:

```
29 mars 2020 22:45 | xxxxxxx@gmail.com | XXX.XXX.XXX.XXX | Tautulli Token Function - Grabbed token from: https://xxxxxxx.com [Execution Time: 606.9ms] |  
-- | -- | -- | -- | --
29 mars 2020 22:45 | xxxxxxxx@gmail.com | XXX.XXX.XXX.XXX | Ombi Token Function - Grabbed token. [Execution Time: 226.7ms] |  
29 mars 2020 22:45 | xxxxx | XXX.XXX.XXX.XXX | Login Function - A User has logged in [Execution Time: 308.8ms]
```

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
Login Error - API connection Failed
```
![image](https://user-images.githubusercontent.com/10527028/77860443-9c440200-720f-11ea-9b8f-1669127a010e.png)

**Comment by HalianElf** [comment] 2020-03-29 20:57
Is your Plex username set in the Admin Username box in the Authentication settings in Organizr?

**Comment by moust4ki** [comment] 2020-03-29 21:02
Hello,
Yes, and it was working flawlessly until now.
![image](https://user-images.githubusercontent.com/10527028/77860777-50925800-7211-11ea-9c6e-38e63ecedd83.png)

Edit: As I said all other accounts can log with Plex SSO, just my admin account has the issue.
The affected account can normally log using the Organizr login/pass. It's just the Plex SSO that is broken on this account only.

**Comment by HalianElf** [comment] 2020-03-29 21:32
Is there anything in the logs? Also, this is oAuth, not SSO. SSO is something else.

**Comment by moust4ki** [comment] 2020-03-29 21:40
Yeah sorry oAuth
For the logs, I just purged them and tried to log using a Plex oAuth on a private browsing:
![image](https://user-images.githubusercontent.com/10527028/77861672-93a2fa00-7216-11ea-8359-b48189d86cb2.png)
![image](https://user-images.githubusercontent.com/10527028/77861679-9ef62580-7216-11ea-9c08-4bca6db375a4.png)

**Comment by causefx** [comment] 2020-03-29 21:51
can you check nginx and php logs?

**Comment by moust4ki** [comment] 2020-03-30 06:37
Here is the log of the Nginx when I try to log using oAuth:
https://pastebin.com/R4LHUSSL
Nginx access.log
https://pastebin.com/41mBdYvR
Nginx error log empty
php error log:
```[30-Mar-2020 08:14:45] NOTICE: fpm is running, pid 341
[30-Mar-2020 08:14:45] NOTICE: ready to handle connections
```

**Comment by moust4ki** [comment] 2020-03-30 11:04
So I also try the following with no luck:

- Change the Plex Administrator to my plex email adress
- Retrieve the Plex Token
- Retrieve the Computer Token
- Restart all dockers
- Restart the whole server
- Try to log with Plex oAuth from an other browser

Still not possible to use Plex oAuth for admin account
Organizr login/pass works
Plex oAuth works for ALL other accounts except the admin one.

FYI I did not make any change between the moment Plex oAuth worked and stopped working: 
I was logged, then I connected to a Friend Organizr webpage, and when I came back to my Organizr browser tab I was logged out. I tried to log as usual using Plex oAuth and it was impossible.

Thanks for your help :)

**Comment by HalianElf** [comment] 2020-03-30 12:54
Seems to be the same issue as #1331 based on your nginx log. Are you up to date?

**Comment by moust4ki** [comment] 2020-03-30 12:57
Hello, yes i'm up to date. 
Do you think it's an issue on Organizr side or Nginx?
Can I do anything to help you debug this ?

I see in the bug report that you link that master branch should be updated "tomorrow" but it was 4 days ago. As i'm running latetst master, it means that the issue is still open?

Thanks :)

**Comment by HalianElf** [comment] 2020-03-30 13:01
Yea it was merged into master. Should be fixed in Version 2.0.408

**Comment by moust4ki** [comment] 2020-03-30 13:02
Thats the version i'm running... :/

**Comment by HalianElf** [comment] 2020-03-30 14:49
Try upping `proxy_buffer_size` in your reverse proxy config?

**Comment by moust4ki** [comment] 2020-03-30 14:52
I'm running https://github.com/Cloudbox/Cloudbox and I have limited knowledge of what I am doing. Should I add it here? (Here is the whole file /opt/nginx-proxy/proxy.conf)
```
# Increase max upload size
client_max_body_size 100G;

# Increase send timeout
send_timeout 100m;

# Increase header buffer size
client_header_buffer_size 64k;
large_client_header_buffers 4 64k;

# Don't disable iframes
proxy_hide_header X-Frame-Options;

```

**Comment by HalianElf** [comment] 2020-03-30 15:23
It looks like it should work if you add it there.

**Comment by moust4ki** [comment] 2020-03-30 15:35
OK but as there is no `proxy_buffer_size` what value should I put?
`proxy_buffer_size 256k;` ?

**Comment by moust4ki** [comment] 2020-03-30 16:01
Looking at nginx documentation I find this:

> **proxy_buffers:** This directive controls the number (first argument) and size (second argument) of buffers for proxied responses. The default is to configure 8 buffers of a size equal to one memory page (either 4k or 8k). Increasing the number of buffers can allow you to buffer more information.
> **proxy_buffer_size:** The initial portion of the response from a backend server, which contains headers, is buffered separately from the rest of the response. This directive sets the size of the buffer for this portion of the response. By default, this will be the same size as proxy_buffers, but since this is used for header information, this can usually be set to a lower value.

So I assume I have to add both lines:
```
proxy_buffer 16k;
proxy_buffer_size 16k;
```
Should I proceed like this ?

**Comment by HalianElf** [comment] 2020-03-30 17:00
Looks like it defaults to either 4k or 8k depending on the system so that sounds like a good starting point to try.

**Comment by moust4ki** [comment] 2020-03-30 17:05
It's not working, nginx won't start if I change this value.
Here is the log:
```│                                                                                                                                                                                                                                                                                                                                               ││    [0;37;1mforego     |  [0mstarting dockergen.1 on port 5000                                                                                                                                                                                                                                                                                 ││    [0;37;1mforego     |  [0mstarting nginx.1 on port 5100                                                                                                                                                                                                                                                                                     ││    [0;33;1mnginx.1    |  [0;31;1m2020/03/30 19:03:48 [emerg] 29#29: "proxy_buffer" directive is not allowed here in /etc/nginx/conf.d/proxy.conf:14                                                                                                                                                                                           ││    [0m [0;37;1mforego     |  [0mstarting nginx.1 on port 5200                                                                                                                                                                                                                                                                                 ││    [0;37;1mforego     |  [0msending SIGTERM to nginx.1                                                                                                                                                                                                                                                                                        ││    [0;37;1mforego     |  [0msending SIGTERM to dockergen.1                                                                                                                                                                                                                                                                                    ││   Custom dhparam.pem file found, generation skipped                                                                                                                                                                                                                                                                                           ││    [0;37;1mforego     |  [0mstarting dockergen.1 on port 5000                                                                                                                                                                                                                                                                                 ││    [0;37;1mforego     |  [0mstarting nginx.1 on port 5100                                                                                                                                                                                                                                                                                     ││    [0;33;1mnginx.1    |  [0;31;1m2020/03/30 19:04:02 [emerg] 28#28: "proxy_buffer" directive is not allowed here in /etc/nginx/conf.d/proxy.conf:14                                                                                                                                                                                           ││    [0m [0;37;1mforego     |  [0mstarting nginx.1 on port 5200                                                                                                                                                                                                                                                                                 ││    [0;37;1mforego     |  [0msending SIGTERM to nginx.1                                                                                                                                                                                                                                                                                        ││    [0;37;1mforego     |  [0msending SIGTERM to dockergen.1                                                                                                                                                                                                                                                                                    ││   Custom dhparam.pem file found, generation skipped                                                                                                                                                                                                                                                                                           ││    [0;37;1mforego     |  [0mstarting dockergen.1 on port 5000                                                                                                                                                                                                                                                                                 ││    [0;37;1mforego     |  [0mstarting nginx.1 on port 5100                                                                                                                                                                                                                                                                                     ││    [0;33;1mnginx.1    |  [0;31;1m2020/03/30 19:04:28 [emerg] 30#30: "proxy_buffer" directive is not allowed here in /etc/nginx/conf.d/proxy.conf:14                                                                                                                                                                                           ││    [0m [0;37;1mforego     |  [0mstarting nginx.1 on port 5200                                                                                                                                                                                                                                                                                 ││    [0;37;1mforego     |  [0msending SIGTERM to nginx.1                                                                                                                                                                                                                                                                                        ││    [0;37;1mforego     |  [0msending SIGTERM to dockergen.1       ```

**Comment by causefx** [comment] 2020-03-30 17:26
try `proxy_buffers 32 4k;`

**Comment by moust4ki** [comment] 2020-03-30 18:09
Ok I tried this setting, Nginx restarted instantly but oAuth is still not working for Admin account :(

**Comment by causefx** [comment] 2020-03-30 18:19
can you post you php location block?

Reason being we need to up these lines or add them:

```
fastcgi_buffers 32 32k;
fastcgi_buffer_size 32k;
```

**Comment by moust4ki** [comment] 2020-03-30 18:34
Sorry but I have no idea what you are talking about... Can you direct me?
Edit:
In the /opt/organizr folder I have the following:
![image](https://user-images.githubusercontent.com/10527028/77948779-36668180-72c6-11ea-8094-d0882fc50823.png)
And also this in the nginx folder:
![image](https://user-images.githubusercontent.com/10527028/77950160-6878e300-72c8-11ea-8fa6-03d3c8e355cb.png)

In the /opt/organizr/nginx/nginx.conf I have this, I think it is what you are looking for:
```
user abc;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules/*.conf;

events {
	worker_connections 768;
}

http {
	##
	# Basic Settings
	##
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# Buffer size for POST submissions
	client_body_buffer_size 512K;
	client_max_body_size 0;
	# Buffer size for Headers
	client_header_buffer_size 1k;
	# Max time to receive client headers/body
	client_body_timeout 12;
	client_header_timeout 12;
	# Hide some headers for security
	fastcgi_hide_header X-Powered-By;
	server_tokens off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Logging Settings
	##
	access_log /config/log/nginx/access.log;
	error_log /config/log/nginx/error.log;

	##
	# Gzip Settings
	##
	gzip on;
	gzip_disable "msie6";

	include /etc/nginx/conf.d/*.conf;
	include /config/nginx/site-confs/*;

}

daemon off;
```

**Comment by causefx** [comment] 2020-03-30 19:07
wait a minute - are you running organizr as a docker container?

**Comment by moust4ki** [comment] 2020-03-30 19:16
Yes, this one: 
organizrtools/organizr-v2:plex

**Comment by causefx** [comment] 2020-03-30 19:26
switch to `organizrtools/organizr-v2:php-fpm` let me know if it still happens

**Comment by moust4ki** [comment] 2020-03-30 19:28
As explained I use a all-in-one system and I cannot (in my limited understanding) switch docker image sources...

**Comment by causefx** [comment] 2020-03-30 19:35
plex isnt the default tag so I'm sure there is a setting to change it.  sorry cant help further.

**Comment by moust4ki** [comment] 2020-03-30 19:40
Well, I tried to change the container and I have a 502 bad gateway so I reverted to the plex one.
Okay too bad. thanks for trying to help me anyway.

Have a nice day and take care :)

**Comment by helangen** [comment] 2020-04-16 10:55
I can confirm that adding:

fastcgi_buffers 32 32k;
fastcgi_buffer_size 32k;

to /config/nginx/nginx.conf under my Docker config works. This fixes the admin login trouble.¨

I am on the latest Organizr v2. 2.0.408.

PS. Before this I tried adding 

proxy_buffer 16k;
proxy_buffer_size 16k;

to the same file as above, but that did not fix the issue.

**Comment by moust4ki** [comment] 2020-04-16 11:50
Added the lines to /opt/organizr/nginx/nginx.conf and restarted the docker but it did not solve the issue.
Here is my nginx.conf:
```user abc;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules/*.conf;

events {
	worker_connections 768;
}

http {
	##
	# Basic Settings
	##
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# Buffer size for POST submissions
	client_body_buffer_size 512K;
	client_max_body_size 0;
	# Buffer size for Headers
	client_header_buffer_size 1k;
	# Max time to receive client headers/body
	client_body_timeout 12;
	client_header_timeout 12;
	# Hide some headers for security
	fastcgi_hide_header X-Powered-By;
	server_tokens off;
	fastcgi_buffers 32 32k;
	fastcgi_buffer_size 32k;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# Logging Settings
	##
	access_log /config/log/nginx/access.log;
	error_log /config/log/nginx/error.log;

	##
	# Gzip Settings
	##
	gzip on;
	gzip_disable "msie6";

	include /etc/nginx/conf.d/*.conf;
	include /config/nginx/site-confs/*;

}

daemon off;```

**Comment by helangen** [comment] 2020-04-16 12:02
That's weird. I use Traefik as a reverse proxy in front of Organizr, but that should not be an issue. I just added the lines and restarted organizr container and then it worked. Don't know what would be the issue. Would you try to rebuild the container? Do you save the conf-files outside the container?

**Comment by moust4ki** [comment] 2020-04-16 12:04
Yeah the config files are saved in /opt/CONTAINERNAME 
I have a limited understanding so as it is only my admin account that cannot connect, I use Organizr backend for it, so I don't F*** everything :D

**Comment by helangen** [comment] 2020-04-16 12:12
I had the same problem as you with the admin account. I had the following errors in nginx.log

2020/04/16 12:44:34 [error] 341#341: *719 upstream sent too big header while reading response header from upstream, client: 172.19.0.7, server: _, request: "POST /api/?v1/login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "sub.domain.com", referrer: "https://sub.domain.com"

These errors went away as soon as I added the above lines and the admin account worked again. What does your log file say?

**Comment by cjattard** [comment] 2020-06-11 20:59
same issue occurred after migrating from OSX/nginx to running docker version behind TraefikV2.

Adding the following lines to nginx.conf also fixed my admin login issue
fastcgi_buffers 32 32k;
fastcgi_buffer_size 32k;

**Comment by moust4ki** [comment] 2020-06-12 12:02
I added those values to proxy.conf in my nginx-proxy folder (Cloudbox), restarted nginx and organizr and it worked :)

**Comment by HalianElf** [comment] 2020-06-12 14:18
This has been documented on the [docs site](https://docs.organizr.app/books/troubleshooting/page/plex-login-error---api-connection-failed) and since the original author has it working now I'm going to close this out.

**Closed as completed by HalianElf** 2020-06-12 14:18 UTC
