### ISSUE TITLE
cURL error 7 on testing

### ISSUE THREAD

**Issue by hackmonker** [causefx/Organizr#1011] opened 2018-12-20 12:11 UTC
###### Operating System: Ubuntu server
<hr>

##### Problem Description:

I installed organizr v2 for the first time and set up plex , sonarr and radarr but nothing appears on the homepage itself . its completely blank. I already set up the homepage Settings but upon testing it gives a error saying `cURL error 7`. ami missing something?

screenshots:

![capture3](https://user-images.githubusercontent.com/46002790/50284139-18cd2a00-047e-11e9-96a0-5e02bfafcddf.PNG)

![capture4](https://user-images.githubusercontent.com/46002790/50284165-27b3dc80-047e-11e9-8312-442ea24dc32d.PNG)

![capture5](https://user-images.githubusercontent.com/46002790/50284180-34d0cb80-047e-11e9-8207-83127b602902.PNG)

<hr>

##### Reproduction Steps:

1. Opened Organizr
2.went to settings and setup homepage items
3.refreshed organizr
4.Only calander is there
5.tested plex connection in homepage items
6.gives error 
`API Connection Failed
cURL error 7:Failed to connect to localhost port 32400: Connection refused` 
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by christronyxyocum** [comment] 2018-12-20 12:57
This is pretty much a duplicate of #1010 that you just recently closed. Is Plex installed on the same Server that you have installed Organizr? The Plex Machine field seems too short to be a real Plex machine ID. You can retrieve the machine ID by browsing to `https://plex.tv/pms/servers?X-Plex-Token=xxxxxxxxxx` and replacing `xxxxxxxxxxx` with your Plex token.

**Comment by hackmonker** [comment] 2018-12-20 13:45
Yeah i did that but testing still says `API Connection Failed cURL error 7:Failed to connect to localhost port 32400: Connection refused`

**Comment by causefx** [comment] 2018-12-20 14:34
try 127.0.0.1

**Comment by hackmonker** [comment] 2018-12-20 14:47
nope same error

**Comment by hackmonker** [comment] 2018-12-20 14:54
Another thing i want to say is that when i go to system settings and try to retrive machine code it gives me only choose plex machine so i have to go to  `https://plex.tv/pms/servers?X-Plex-Token=xxxxxxxxxx`
and then get my machine code

![capture8](https://user-images.githubusercontent.com/46002790/50291599-05798900-0495-11e9-9e02-64b7ab5238e5.PNG)

**Comment by jonfinley** [comment] 2018-12-20 14:59
okay slow down. is org and plex installed on the same machine? I assume from the previous comments on both reddit and #1010 that you are running docker.

**Comment by jonfinley** [comment] 2018-12-20 15:01
Your **PLEX** ip needs to be the _host_ machine ip not the loopback. same goes with any other docker instances on the homepage they all need to be the host machine.

**Comment by hackmonker** [comment] 2018-12-20 15:12
well yeah you are right about that I am running it in docker but plex opens in webpage through http://localhost:32400 so why doesnt organizr recognize that? sorry i really am a noob4life!

**Comment by hackmonker** [comment] 2018-12-20 15:57
Also i did not state that that evrything is running off a vm. plex is installed directly in vm while sonnar and raddar are instaled as docker containers. now VMs provide a static ip to all processes via NAT which is 10.0.2.15, which cannot be accessed via host. So i had to port forward 10.0.2.15 on port 32400 to 127.0.0.1:32400 and i can access plex on my host through local host . i tried putting my host ip 192.168.xxxx.xx as the ip in place of 127.0.0.1 during port forwarding but then plex cant find my server. well thats the gist.

**Comment by christronyxyocum** [comment] 2018-12-20 16:35
`localhost` and `127.0.0.1` mean that specific machine, not remote in any way, and, from your above statement, Plex and Organizr are not on the same machine, or even the same network. So it seems that you have internal network communication problems that are causing all of this and they need to be sorted out first. You shouldn't have to do any level of port forwarding for machines on your network to be bale to communicate. VMs should be in bridge mode so that they get an IP address on your existing local network. It's one thing to be using multiple subnets within the same IP range, but different ranges entirely make it a much more difficult setup to work with.

**Comment by hackmonker** [comment] 2018-12-20 16:40
wooo ! finally it worked thanks a lot guys. I guess it was a claim problem.  what i did was forwarded my guest os port 32400 to my host port 32400. Also i used the host ip as my ip instead of loopback address. then I went to the docker config and then got another claim key and restarted plex and it can now see my server . Also put the host ip in home page settings and it worked. Thanks a lot and really enjoyed the software so far. Keep up the goodwork!!

**Comment by hackmonker** [comment] 2018-12-20 16:45
ok just one question ....what was the url for the homepage...sorry I deleted the homepage tab in anger. hahaha!

**Comment by christronyxyocum** [comment] 2018-12-20 16:48
Glad you got it working. The URL is `api/?v1/homepage/page` for the homepage and it should be set to type `Internal` on the main Tab Editor page.

Please close this as solved and do the same with your Reddit topic.

**Comment by hackmonker** [comment] 2018-12-20 16:50
ok just one question ....what was the url for the homepage...sorry I deleted the homepage tab in anger. hahaha!

**Comment by hackmonker** [comment] 2018-12-20 16:51
alright thanks

**Closed** 2018-12-20 16:51 UTC
