### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by kvalle22** [causefx/Organizr#1972] opened 2024-03-25 20:54 UTC
##### Problem Description:

![image](https://github.com/causefx/Organizr/assets/26128231/9cbd8cd9-c8c1-459a-85d5-9196e376e2ae)
I restarted the pc and this message shows when I try to open Organizr
<hr>

##### Reproduction Steps:

I have no idea I just restarted the PC
<hr>

#### Errors on screen?  If so paste here:

```
502 Bad Gateway
nginx/1.18.0
```
```
\php_errors.log
[25-Mar-2024 20:24:39 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:26:06 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:31:47 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:38:01 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:38:03 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:38:05 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:38:06 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
[25-Mar-2024 20:38:10 UTC] PHP Fatal error:  Unknown: Failed opening required 'Standard input code' (include_path='.;C:\php\pear') in Unknown on line 0
```

```
\error.log
2024/01/21 19:45:38 [notice] 20976#25080: signal process started
2024/01/21 19:46:04 [notice] 21104#20884: signal process started
2024/01/21 19:46:43 [error] 16568#27468: *12 CreateFile() "c:/nginx/www/organizr/html/plugins/bower_components/owl.carousel/owl.video.play.png" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /plugins/bower_components/owl.carousel/owl.video.play.png HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/01/21 20:06:12 [error] 22892#21692: *74 CreateFile() "c:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/api/v2/page/settings"
2024/02/04 00:20:01 [error] 5624#5692: *46 CreateFile() "c:/nginx/www/organizr/html/js/tinycolor.min.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /js/tinycolor.min.map HTTP/1.1", host: "localhost"
2024/02/04 00:20:01 [error] 5624#5692: *45 CreateFile() "c:/nginx/www/organizr/html/js/plyr.js.map" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /js/plyr.js.map HTTP/1.1", host: "localhost"
2024/02/15 09:59:55 [notice] 9692#18156: signal process started
2024/02/21 23:48:33 [error] 6500#6552: *45 CreateFile() "c:/nginx/www/organizr/html/plugins/bower_components/owl.carousel/owl.video.play.png" failed (2: The system cannot find the file specified), client: 192.168.18.11, server: localhost, request: "GET /plugins/bower_components/owl.carousel/owl.video.play.png HTTP/1.1", host: "192.168.18.9", referrer: "http://192.168.18.9/"
2024/03/16 22:59:52 [error] 4732#5388: *18 CreateFile() "c:/nginx/www/organizr/html/plugins/bower_components/owl.carousel/owl.video.play.png" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /plugins/bower_components/owl.carousel/owl.video.play.png HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/16 22:59:55 [error] 4732#5388: *18 CreateFile() "c:/nginx/www/organizr/html/plugins/bower_components/owl.carousel/owl.video.play.png" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /plugins/bower_components/owl.carousel/owl.video.play.png HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:23:41 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:23:43 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:23:43 [error] 10232#9964: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:23:45 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:23:51 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:23:53 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:23:53 [error] 10232#9964: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:23:56 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:24:11 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:24:13 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:24:13 [error] 10232#9964: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:24:15 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:24:47 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:24:49 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:24:49 [error] 10232#9964: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:24:51 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:24:55 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:24:57 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:24:57 [error] 10232#9964: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:24:59 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:25:02 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:25:04 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:25:04 [error] 10232#9964: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:25:06 [error] 10232#9964: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:26:14 [error] 1948#13972: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:26:16 [error] 1948#13972: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:26:16 [error] 1948#13972: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:26:18 [error] 1948#13972: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:26:28 [error] 1948#13972: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:26:30 [error] 1948#13972: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:26:30 [error] 1948#13972: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:26:32 [error] 1948#13972: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:31:53 [error] 15104#20372: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:31:55 [error] 15104#20372: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:31:56 [error] 15104#20372: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:31:58 [error] 15104#20372: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:35:49 [error] 15104#20372: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:35:51 [error] 15104#20372: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:35:51 [error] 15104#20372: *6 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:35:53 [error] 15104#20372: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:37:51 [error] 15104#20372: *11 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:37:54 [error] 15104#20372: *11 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:37:54 [error] 15104#20372: *11 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:37:56 [error] 15104#20372: *11 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:42:40 [error] 15104#20372: *17 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:42:42 [error] 15104#20372: *17 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:42:42 [error] 15104#20372: *17 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:42:44 [error] 15104#20372: *17 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:44:09 [error] 15104#20372: *22 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:44:11 [error] 15104#20372: *22 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:44:11 [error] 15104#20372: *22 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:44:13 [error] 15104#20372: *22 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:45:54 [error] 15104#20372: *27 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:45:56 [error] 15104#20372: *27 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:45:57 [error] 15104#20372: *27 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:45:59 [error] 15104#20372: *27 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:45:59 [error] 15104#20372: *29 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:46:01 [error] 15104#20372: *29 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:46:01 [error] 15104#20372: *29 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:46:03 [error] 15104#20372: *29 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:46:38 [error] 22404#1412: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:46:40 [error] 22404#1412: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:46:40 [error] 22404#1412: *1 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:46:42 [error] 22404#1412: *1 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:48:48 [error] 22404#1412: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:48:50 [error] 22404#1412: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
2024/03/25 15:48:50 [error] 22404#1412: *6 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2024/03/25 15:48:52 [error] 22404#1412: *6 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"

```

**Comment by tronyx** [comment] 2024-03-25 21:26
OP reached out for support in Discord ~5 minutes after opening this. Issue caused by them changing their Windows password. Closing.

**Closed as completed by tronyx** 2024-03-25 21:26 UTC
