### ISSUE TITLE
Eating up a lot of memory on the client over time

### ISSUE THREAD

**Issue by medom** [causefx/Organizr#159] opened 2017-03-17 08:44 UTC
I dont know if this is an actual issue, a single bad boy, or just that this many iframes cause trouble sooner or later - I am running ~10 apps (the usual suspects, sonarr etc) in Organizr. However I noticed that over time (night), the system task (on macOS) of my Organizr tab in Chrome went up to 15G of memory usage, maxing out my RAM and resulting in an unresponsive system.

I would like to leave the Organizr tab open (pinned) at all times, so I'm not sure if this is the right approach for me vs just going back to single tabs (that didnt exceed my memory though).

Anyone else experiencing this?

**Comment by causefx** [comment] 2017-03-17 14:57
I have over 13 Tabs open in Organizr plus my normal tabs in Chrome.  RAM usage is minimal.

**Comment by causefx** [comment] 2017-03-18 22:11
@medom were you able to keep replicating this?  or find the root cause?

**Comment by causefx** [comment] 2017-03-19 17:29
closing for now, reply if something comes up and we will investigate.

**Closed by causefx** 2017-03-19 17:29 UTC

**Comment by jethromorais** [comment] 2020-05-10 14:26
Hey guys, sorry to open an old issue, but I'm having this issue... On my case is with Firefox, it takes a couple of days, but today as an example, organizr tab was using 10gb of RAM...
I normally keep a few tabs open, Organizr , plex , sonarr , tautulli and rarbg ;-) thei morning Firefox was using 12GB of RAM, and Organizr tab was stuck... After I close Organizr, RAM usage dropped to 1.5GB for Firefox and everything went back to normal.

**Comment by causefx** [comment] 2020-05-10 15:03
Try leaving organizr open with only the settings page being the only open tab. check the memory issue there after a few days. usually the high memory issue is caused by another apps tab within organizr.

**Comment by jethromorais** [comment] 2020-05-10 15:06
Will do :-)
I'll report back in a few days.
