### ISSUE TITLE
Unable to get past SSO screen in Tautulli 2.5.3

### ISSUE THREAD

**Issue by PearsonFlyer** [causefx/Organizr#1430] opened 2020-07-15 19:22 UTC
###### Operating System: Windows/MacOS/Ubuntu

Organizr Version: 2.0.650
Branch:  Master
WebServer: Nginx
OS: Windows 10

##### Problem Description:
After Tautulli's latest update, after the SSO signin and Plex authorization screens, it goes back to the SSO signin screen. I can never get Tautulli to actually load. When loading in a new non-Organizr tab on the same machine in the same browser, it works fine.

Per SwiftPanda, I had previously cleared all cookies and cache from my browser. I have also tried multiple browsers, with the same outcome.  When I test the tab, it warns me that I now need to set Tautulli as "new window", which I did not have to do prior to this update. SP16 suggested I open an issue here.

<hr>

##### Reproduction Steps:
Go to Tautulli tab in Organizr. Log in using Plex credentials. Goes back to same login screen.
Tautulli is running in a reverse proxy, SSL, on another machine on the network.

<hr>

#### Errors on screen?  If so paste here:

```
Errors in Organizr log:

Plex Connect Function - Error: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received [Execution Time: 10.34s | 10347.9ms]

```

**Comment by causefx** [comment] 2020-07-15 20:15
tautulli proxied via subfolder or subdirectory?

**Comment by PearsonFlyer** [comment] 2020-07-15 20:16
It's at https://mydomain/tautulli

**Comment by PearsonFlyer** [comment] 2020-07-15 20:17
Here is my nginx section:

```
      location /tautulli/ {
               #auth_request /auth-admin;
               add_header X-Frame-Options "SAMEORIGIN";
               proxy_set_header Host $host;
               proxy_set_header X-Forwarded-Host $server_name;
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Ssl on;
               proxy_set_header X-Forwarded-Proto $scheme;

               proxy_pass http://127.0.0.1:8181;
               proxy_redirect http://127.0.0.1:8181 https://$host;
       }
```

**Comment by causefx** [comment] 2020-07-15 20:19
@HalianElf I believe you have tau in subfolder, are you seeing the same issue?  I have it on subdomain with no issue.

**Comment by HalianElf** [comment] 2020-07-15 20:23
It was doing that right after the update... Logging out of Organizr, clearing cache and logging back in seemed to fix it.

**Comment by causefx** [comment] 2020-07-15 20:24
@HalianElf can you add my username to your tautulli to see if SSO will work for me

**Comment by causefx** [comment] 2020-07-15 20:31
@PearsonFlyer I just tried logging into elf's organizr and it gave me access to ther Tau.

![image](https://user-images.githubusercontent.com/16184466/87592835-6122ed00-c69f-11ea-8cd1-653bef90ce14.png)

as you can see it created the cookie.  Can you paste your tau SSO settings here pelase?

**Comment by PearsonFlyer** [comment] 2020-07-15 20:45
I'm not sure specifically what you're asking for. I don't see any SSO settings in the Tau settings screens except for this option, which is checked:  Allow Plex Admin

I do not have other users on my Organizr or Tautulli, if that makes any difference.

**Comment by PearsonFlyer** [comment] 2020-07-15 20:48
After logging in using SSO, on the standalone screen, I do get a tautulli_token cookie like above. But on the Organizr login it does not create one if I have cleared cookies, and if I go there and try to log in with the cookie existing, it does not list one at all.

**Comment by HalianElf** [comment] 2020-07-15 21:03
I'm assuming by logging with SSO you're referring to logging in using oAuth. The SSO settings are in Organizr: 
![image](https://user-images.githubusercontent.com/28244771/87595783-17e19600-c6bd-11ea-815b-9dc981a8a86d.png)

**Comment by PearsonFlyer** [comment] 2020-07-15 21:26
Oh, gotcha.  I have the same domain/tautulli setting I have in the tab editor.

Looking at your settings, I've changed it to the format you have and it's the same effect.  This time, I got an email from Plex about a new login to my account though, so something has improved.

**Comment by causefx** [comment] 2020-07-15 21:32
yeah, on SSO settings for Tautulli - you need to make sure it ends in `/tautulli` or whatever your subdir is.... It should be settings that domain with that path.

**Comment by PearsonFlyer** [comment] 2020-07-15 21:39
Ok.  On my SSO settings now, I have http://ipaddress:8181/tautulli. Still does not work, but after logging in via Plex window, I got an email about a new Plex login.  Now, though, nothing at all shows up in the logs.  In my Tautulli logs, I get a login attempt though:

Tautulli WebAuth :: Admin user 'myuser' logged into Tautulli using Plex OAuth login.

And I have an entry in my Tautulli login logs.

**Comment by causefx** [comment] 2020-07-15 21:43
@HalianElf can you share your nginx config for tau?

**Comment by HalianElf** [comment] 2020-07-15 21:45
It's just the one that comes with LE basically with a couple extra blocks for the newsletter but yea when I get back home I can.

**Comment by PearsonFlyer** [comment] 2020-07-15 21:55
Now in my console, I noticed I get this error:  

Blocked autofocusing on a form control in a cross-origin subframe. Login:79

When I hover over Login:79, it shows this URL:

http://192.168.1.84:8181/tautulli/auth/login?redirect_uri=/tautulli/home

**Comment by HalianElf** [comment] 2020-07-16 00:14
This is what I'm using 
```nginx
location ^~ /tautulli {
    auth_request /auth-4;

    include /config/nginx/proxy.conf;
    #resolver 127.0.0.11 valid=30s;
    set $upstream_app tautulli;
    set $upstream_port 8181;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}

location ^~ /tautulli/api {
    include /config/nginx/proxy.conf;
    #resolver 127.0.0.11 valid=30s;
    set $upstream_app tautulli;
    set $upstream_port 8181;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}

location ^~ /tautulli/newsletter {
    include /config/nginx/proxy.conf;
    #resolver 127.0.0.11 valid=30s;
    set $upstream_app tautulli;
    set $upstream_port 8181;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}

location ^~ /tautulli/image {
    include /config/nginx/proxy.conf;
    #resolver 127.0.0.11 valid=30s;
    set $upstream_app tautulli;
    set $upstream_port 8181;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

**Comment by causefx** [comment] 2020-07-16 00:23
is your proxy.conf edited from original?

**Comment by HalianElf** [comment] 2020-07-16 00:27
Other than increasing the proxy_buffers for the header issue, it's the original.
```nginx
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
```

**Comment by PearsonFlyer** [comment] 2020-07-16 00:27
I tried this (changing to .1 and commenting out the include I don't have), same thing but no login:79 error in the console. I am still able to hit it outside of Organizr though.

I do still get the Tautulli log entry that says "Tautulli WebAuth :: Admin user 'myuser' logged into Tautulli using Plex OAuth login."

The login is working, the redirect back to the Tautulli home page is not. Instead it goes back to the SSO screen.

**Comment by PearsonFlyer** [comment] 2020-07-20 11:01
Is there any additional info I can provide on resolving this? I'd love to get Tautulli back into my frames on Organizr and save myself an always-open tab. Thank you all for your help, I'm so close.

**Comment by tronyx** [comment] 2020-07-21 11:04
@PearsonFlyer Did you try what @HalianElf recommended? You never acknowledged her response:

> 
> 
> It was doing that right after the update... Logging out of Organizr, clearing cache and logging back in seemed to fix it.

Same thing with @causefx question:

> 
> 
> is your proxy.conf edited from original?

**Comment by PearsonFlyer** [comment] 2020-07-21 11:06
Yes, I have logged out of Organizr, cleared the cache, and logged back in, multiple times on multiple browsers. I mentioned this in my original post.

The causefx question about proxy.conf was a question to @HalianElf - I do not have a proxy.conf file as I mentioned in my reply.

**Comment by PearsonFlyer** [comment] 2020-07-25 22:06
One more ping on this to see if there's a way to resolve it. If not, I'll peacefully leave Tautulli open in a separate window, but that extra tab bugs me when I know there's a solution I just can't see.

**Comment by HalianElf** [comment] 2020-07-25 23:24
I honestly have no idea why it's not working for you as long as your Organizr and Tautulli are on the same domain.

**Comment by causefx** [comment] 2020-07-25 23:56
I too have no clue what could be causing it to not work here.  We both tested subdomain and subdirectory with no issue.  I will look into increasing the timeout to fix the initial error you posted on first post.

**Comment by notinhell** [comment] 2020-07-28 18:52
I'm experiencing the exact same issue. My differences are that I'm not using SSO just attempting to log into Tautulli directly and not using a reverse proxy. If it's set to open within the iframe I attempt to log in and am just redirected back to the Tautulli login page. If I choose to open a new tab everything works without issue. I also don't see any errors in the Organizr logs at all. I've gone through all applicable suggestions mentioned here and the issue has persisted.

**Comment by Potjoe-97** [comment] 2020-07-28 19:07
I have the exact same situation as@notinhell. I'm trying to access Tautulli's tab in Iframe mode and I'm not using a reverse proxy. Tab's url is set to http://tautulli.home:8181. Same here, while the authentication is successful in the plex auth popup, it just refresh the login page in tab.

**Comment by causefx** [comment] 2020-07-28 19:55
@notinhell @Potjoe-97 both of your issues are caused by:


https://docs.organizr.app/books/troubleshooting/page/redirect-looping---samesite-errors

**Comment by Potjoe-97** [comment] 2020-07-28 20:17
Thanks for your reply. I had a look and unfortunately, still no luck. 
In my case a pfSense routeur is handling host override through the DNS 
Resolver (which corresponds to Option #1 in the way you linked). Thus, 
there is already a DNS A record for tautulli.home, resolving into my 
local ip, 192.168.40.3 (same subnet as organizr, which has the same 
kind of DNS record).

**Comment by HalianElf** [comment] 2020-07-29 15:36
I don't think going to work with just a `<name>.tld` since that would be considered a separate domain which falls under the same thing.

**Comment by Potjoe-97** [comment] 2020-07-29 16:01
I understand. Maybe I can try to move tautulli to the same ip than organizr, since I'm using docker versions. All my network is configured to use local domain .home, but they are still different hosts.

**Comment by daephx** [comment] 2020-08-01 07:25
+1 I'm not keen on how to configure a proxy, let alone what might be needed to suppress this login loop but just to add... 
A similar issue is happening with the password prompt on Deluge WebUI under <iframe>.
All seem to work fine as there own window/tab at the least. (Deluge, tautulli, jackett)

**Comment by HalianElf** [comment] 2020-08-01 16:13
@daephx Did you read the link that @causefx posted? You don't need to proxy anything, you can use the host file (or local DNS through something like pihole or your router if it supports it) to put them all on the same subdomain locally.

**Comment by Potjoe-97** [comment] 2020-08-01 16:50
@HalianElf My bad, I did'nt get it the first time you said it. Setting tautulli.subdomain.tld and organizr.subdomain.tld as DNS records in pfsense solve the issue.

**Comment by daephx** [comment] 2020-08-01 22:41
@HalianElf I did and the entry at the bottom initially indicated to me that a proxy would be required to square 'everything' up.
quote: "The only way to bypass that is to use Option 1 and Option 2"

After modifying the etc/hosts and disabling samesite, it appears that deluge is no longer acting up but I'm seeing no change in tautulli or jackett which is kinda what I expected.

**Comment by HalianElf** [comment] 2020-08-01 23:10
Option #1 is internal DNS/host file... how does that mean you need a proxy?

**Comment by daephx** [comment] 2020-08-01 23:39
@HalianElf I have already implemented options 1&3, I was leaning toward how option 2 is rather sparse and alludes to the need for a proxy but is stated at the bottom as a requirement for `Lax` cookies.

**Comment by HalianElf** [comment] 2020-08-02 00:21
I'll change it to an or... Either of options 1 or 2 should work.

**Comment by causefx** [comment] 2020-09-17 21:14
@PearsonFlyer same issue still?

**Comment by PearsonFlyer** [comment] 2020-09-17 22:06
I reactivated the tab and tried again, and now after the Plex login box pops up and I authenticate, it goes back to the login screen like I did not just log in.  Just for the heck of it, I also tried using my Tautulli login, and same thing.

**Comment by causefx** [comment] 2020-09-17 22:19
is this logging straight into tau from a tab or logging into Organizr and then going into tab?

**Comment by PearsonFlyer** [comment] 2020-09-17 22:26
This is from within Organizr in a tab. Standalone it works fine, so I've been running Tau that way since I reported this issue initially.

I just can't get past the login through Organizr.

**Comment by thousandbuckle** [comment] 2020-11-16 23:52
I am having the exact same issue. Windows 10; Organizr 2.1.74 v2-master; PHP 7.4.8; nginx/1.18.0. When I set Tautulli to iFrame it keeps looping me back to the Tautulli login page but works fine as New Window. Has any one figured out what the problem is? I am not running any reverse proxy or pfSense.

**Comment by HalianElf** [comment] 2020-11-17 00:00
Is your Organizr and Tautulli on the same PC @thousandbuckle?

**Comment by causefx** [comment] 2021-01-21 22:28
is this still happening with everyone?

**Comment by PearsonFlyer** [comment] 2021-01-21 23:32
Yes. Still happening here, I'm on the latest version 2.1.120.

**Comment by causefx** [comment] 2021-01-22 01:08
for shits and giggles have you tried setting up tautulli on subdomain?
edit:
I also just confirmed with swift his settings:
![image](https://user-images.githubusercontent.com/16184466/105433460-de16bc80-5c16-11eb-983f-734af2f3e1c9.png)

**Comment by causefx** [comment] 2021-01-22 01:13
I wonder if it is a timeout issue.  I will increase the timeout.

**Comment by causefx** [comment] 2021-01-22 21:59
Organizr was updated today to increase the timeout...  Can you update and try again?  Also post some logs after login to see what it is doing.

**Comment by PearsonFlyer** [comment] 2021-01-22 22:29
Updated and still no-go. The logs don't seem to log any of the login stuff.

In the nginx error log, I have this:

`2021/01/22 17:12:20 [error] 4204#8296: *17193 FastCGI sent in stderr: "PHP Warning:  array_column() expects parameter 1 to be array, null given in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 261
PHP Warning:  array_search() expects parameter 2 to be array, null given in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 261
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 266
PHP Notice:  Undefined offset: 0 in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 262
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 266
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 263
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 263
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 264
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 264
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 265
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 266
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 263
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 263
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 264
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 264
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 265
PHP Notice:  Undefined index: rating_key in C:\nginx\www\organizr\html\api\homepage\tautulli.php on line 266`

The actual Organizr log only has this:

`

January 22, 2021 5:18 PM | Me | 127.0.0.1 | Admin Function - Accessed Settings Page [Execution Time: 26ms] |  
-- | -- | -- | -- | --
January 22, 2021 5:18 PM | Me | 127.0.0.1 | Tautulli Token Function - Grabbed token from: http://192.168.1.84:8181/tautulli/home [Execution Time: 178.9ms] |  
January 22, 2021 5:18 PM | Me | 127.0.0.1 | Login Function - A User has logged in [Execution Time: 240.4ms] |  

`

**Comment by causefx** [comment] 2021-01-22 22:51
So it is grabbing a token from Tautulli, not sure why it says /home on url for Tautulli.  So it seems it is having trouble actually setting the Cookie.  

judging by the url given it would try and set the cookie path to `/tautulli/home` 
![image](https://user-images.githubusercontent.com/16184466/105557521-b16fad00-5cc9-11eb-82d1-4f53f4575c0c.png)

Can you remove /home from the url?  then logout and back in

**Comment by PearsonFlyer** [comment] 2021-01-22 23:39
Now I get an error on the token grab.


January 22, 2021 6:37 PM | Me | 127.0.0.1 | Admin Function - Accessed Settings Page [Execution Time: 20.2ms] |  
-- | -- | -- | -- | --
January 22, 2021 6:37 PM | Me | 127.0.0.1 | Tautulli Token Function - Error on URL: http://192.168.1.84:8181/tautulli [Execution Time: 133.3ms] |  
January 22, 2021 6:37 PM | Me | 127.0.0.1 | Login Function - A User has logged in [Execution Time: 207.8ms] |

**Comment by causefx** [comment] 2021-01-23 17:42
is this using user/pass or plex oauth?

**Comment by PearsonFlyer** [comment] 2021-01-23 17:57
Plex oauth

**Comment by MichaelTrip** [comment] 2021-03-10 12:55
I have the same issue while using a subdomain. Is there anything i can do to supply you with some information etc?

**Closed as completed** 2021-06-25 03:37 UTC
Labels: no-issue-activity, closed-no-issue-activity
