### ISSUE TITLE
PHP warnings in check.php

### ISSUE THREAD

**Issue by hoopty** [causefx/Organizr#22] opened 2017-01-04 16:27 UTC
I get the following warnings from check.php, please fix or suppress:
```
PHP Warning:  dirname() expects exactly 1 parameter, 2 given in /usr/local/www/data/check.php on line 77" while reading response header from upstream, client: 192.168.1.112, server: localhost, request: "GET /check.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "web.local"
PHP Warning:  dirname() expects exactly 1 parameter, 2 given in /usr/local/www/data/check.php on line 78" while reading upstream, client: 192.168.1.112, server: localhost, request: "GET /check.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "web.local"
PHP Warning:  dirname() expects exactly 1 parameter, 2 given in /usr/local/www/data/check.php on line 130" while reading upstream, client: 192.168.1.112, server: localhost, request: "GET /check.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "web.local"
```

PHP info:
```
phpinfo()
PHP Version => 5.6.29

System => FreeBSD web.local 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
Build Date => Dec 13 2016 04:39:08
Configure Command =>  './configure'  '--with-layout=GNU' '--localstatedir=/var' '--with-config-file-scan-dir=/usr/local/etc/php' '--disable-all' '--enable-libxml' '--enable-mysqlnd' '--with-libxml-dir=/usr/local' '--with-pcre-regex=/usr/local' '--with-zlib-dir=/usr' '--program-prefix=' '--enable-fpm' '--with-fpm-user=www' '--with-fpm-group=www' '--with-regex=php' '--with-zend-vm=CALL' '--disable-ipv6' '--prefix=/usr/local' '--mandir=/usr/local/man' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd11.0' 'build_alias=amd64-portbld-freebsd11.0' 'CC=cc' 'CFLAGS=-O2 '-pipe' '-fstack-protector' '-fno-strict-aliasing'' 'LDFLAGS= '-fstack-protector'' 'LIBS=-lpthread' 'CPPFLAGS=' 'CPP=cpp' 'CXX=c++' 'CXXFLAGS=-O2 '-pipe' '-fstack-protector' '-fno-strict-aliasing'
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /usr/local/etc
Loaded Configuration File => /usr/local/etc/php.ini
Scan this dir for additional .ini files => /usr/local/etc/php
Additional .ini files parsed => /usr/local/etc/php/ext-18-session.ini,
/usr/local/etc/php/ext-20-filter.ini,
/usr/local/etc/php/ext-20-hash.ini,
/usr/local/etc/php/ext-20-json.ini,
/usr/local/etc/php/ext-20-pdo.ini,
/usr/local/etc/php/ext-30-pdo_sqlite.ini

PHP API => 20131106
PHP Extension => 20131226
Zend Extension => 220131226
Zend Extension Build => API220131226,NTS
PHP Extension Build => API20131226,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => disabled
IPv6 Support => disabled
DTrace Support => disabled

Registered PHP Streams => php, file, glob, data, http, ftp
Registered Stream Socket Transports => tcp, udp, unix, udg
Registered Stream Filters => string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

This program makes use of the Zend Scripting Language Engine:
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

Thanks!

**Comment by causefx** [comment] 2017-01-04 16:51
fixed on my end, will commit when I get home.  This was caused by including a parameter for PHP 7.

**Closed** 2017-01-06 06:28 UTC
Labels: bug
