### ISSUE TITLE
Gateway Timeout on User creation

### ISSUE THREAD

**Issue by tdunks** [causefx/Organizr#384] opened 2017-06-12 20:21 UTC
I am currently getting a gateway timeout whenever I try to create a user account. The user does create, but it hands for my full timeout time (120s) before giving me a nginx 502 error.

Checking my nginx logs I have

`2017/06/12 15:15:08 [error] 1185#1185: *1447 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.2.1, server: website.com, request: "POST /settings.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock", host: "website.com", referrer: "https://website.com/settings.php"
`

**Comment by causefx** [comment] 2017-06-13 06:11
can you email me the URL and registration password?  causefx at me dot com

**Comment by causefx** [comment] 2017-06-16 00:03
this was caused by an email setting, fixed now.

**Closed by causefx** 2017-06-16 00:03 UTC
